name: Deploy MassiveWiki to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
	working-directory: .massivewikibuilder/massivewikibuilder

    - name: install node modules
      run: |
        npm ci
	working-directory: .massivewikibuilder/massivewikibuilder

    - name: Build website
      run: |
        ./mwb.py -c ../mwb.yaml -w ../.. -o ../../output -t ../this-wiki-themes/basso --lunr --commits
	working-directory: .massivewikibuilder/massivewikibuilder

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
